micronaut:
  application:
    name: user
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/user_db?ssl=false
    username: root
    password: app
    driverClassName: org.mariadb.jdbc.Driver
    maximumPoolSize: 50